/**
 * Central SEO configuration for GŌKAI.
 *
 * ⚠️  PRODUCTION DOMAIN – ACTION REQUIRED
 * Organic search authority accumulates on the canonical domain.
 * The current fallback points to the Vercel preview URL, which is
 * suboptimal for long-term SEO.
 *
 * Before launching SEO campaigns:
 *   1. Buy / assign a primary domain (e.g. https://www.gokai.com.br)
 *   2. Set NEXT_PUBLIC_APP_URL in Vercel → Project Settings → Environment Variables
 *   3. Set the same variable in .env.local for local development
 *   4. Verify Google Search Console and Bing Webmaster Tools against that domain
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_APP_URL ?? "https://gokai-web.vercel.app"
).replace(/\/$/, "")

/**
 * Returns the absolute canonical URL for a given path.
 *
 * @param path - An absolute path starting with "/", e.g. "/sobre"
 * @example
 *   canonicalUrl("/sobre")
 *   // → "https://gokai-web.vercel.app/sobre"
 */
export function canonicalUrl(path: string): string {
  return `${SITE_URL}${path}`
}

export const siteConfig = {
  name: "GŌKAI",
  fullName: "GŌKAI – Associação Esportiva e Ambiental",
  /**
   * Public-facing description used in root metadata and Open Graph tags.
   * Focused on the user offer, not on internal platform language.
   */
  description:
    "Associação de artes marciais que forma atletas e cidadãos por meio da disciplina, do respeito e da evolução contínua.",
  url: SITE_URL,
} as const

// ─── Default OG image ─────────────────────────────────────────────────────────

/**
 * Default Open Graph image for social sharing previews.
 *
 * Default OG image route generated by Next.js.
 * A custom branded image can replace this later, but this path must always exist.
 */
export const DEFAULT_OG_IMAGE = "/opengraph-image"

// ─── Open Graph helper ────────────────────────────────────────────────────────

type OgType = "website" | "article"

interface PageOpenGraphOptions {
  title: string
  description: string
  /** Absolute URL path starting with "/", e.g. "/sobre" */
  path: string
  /** Falls back to DEFAULT_OG_IMAGE when omitted */
  imageUrl?: string | null
  type?: OgType
}

/**
 * Builds a consistent openGraph object for any public marketing page.
 * Always includes the default OG image so social previews never go blank.
 */
export function pageOpenGraph({
  title,
  description,
  path,
  imageUrl,
  type = "website",
}: PageOpenGraphOptions) {
  return {
    type,
    title,
    description,
    siteName: siteConfig.name,
    url: canonicalUrl(path),
    locale: "pt_BR",
    images: [
      {
        url: imageUrl ?? DEFAULT_OG_IMAGE,
        width: 1200,
        height: 630,
        alt: title,
      },
    ],
  }
}

// ─── Twitter / X card defaults ────────────────────────────────────────────────

/**
 * Default Twitter card type.
 * Spread this into page metadata `twitter` fields and add page-specific
 * title / description / images as needed.
 *
 * @example
 *   twitter: { ...twitterCard, title: "...", description: "..." }
 */
export const twitterCard = {
  card: "summary_large_image",
} as const

// ─── Organization JSON-LD ─────────────────────────────────────────────────────

import {
  CONTACT_EMAIL,
  CONTACT_PHONE_HREF,
  CONTACT_ADDRESS_SCHEMA,
  SOCIAL_PROFILES,
} from "@/lib/site"

/**
 * Organization structured data (Schema.org / JSON-LD) for the root site.
 *
 * Contact data, address, and social profiles are sourced from `src/lib/site.ts`.
 * Fields with null values are omitted from the output — no fake data is emitted.
 *
 * ⚠️  ACTION REQUIRED:
 *   logo   → Replace /public/assets/branding/* if new official brand files arrive
 *   Others → Fill in src/lib/site.ts with confirmed real-world data
 */
export const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "SportsOrganization",
  name: siteConfig.fullName,
  alternateName: siteConfig.name,
  url: siteConfig.url,
  description: siteConfig.description,
  logo: `${SITE_URL}/assets/branding/gokai-logo.png`,
  // Conditionally include contact fields — only when real data is set in site.ts
  ...(CONTACT_EMAIL ? { email: CONTACT_EMAIL } : {}),
  ...(CONTACT_PHONE_HREF ? { telephone: CONTACT_PHONE_HREF } : {}),
  ...(CONTACT_ADDRESS_SCHEMA
    ? {
        address: {
          "@type": "PostalAddress",
          ...CONTACT_ADDRESS_SCHEMA,
        },
      }
    : {}),
  sameAs: SOCIAL_PROFILES,
}

// ─── Crawl / index control ────────────────────────────────────────────────────

/**
 * Robots metadata for non-public routes.
 *
 * Indexing strategy for GŌKAI:
 *
 *   INDEXABLE  → (marketing) route group — /, /sobre, /modalidades, /professores,
 *                /eventos, /eventos/[slug], /transparencia, /governanca,
 *                /patrocinadores, /apoiadores, /contato, /privacidade
 *
 *   NOINDEX    → (auth) route group — /login, /esqueci-senha, /redefinir-senha
 *
 *   NOINDEX    → (app) route group — all /app/* private authenticated surfaces
 *
 * robots.ts also disallows these paths at the crawler level as a belt-and-suspenders
 * safeguard. Route-level metadata wins for compliant crawlers even if robots.txt
 * is bypassed.
 *
 * Usage — spread into any layout.tsx that must never appear in search results:
 *
 *   export const metadata: Metadata = { ...noIndexMetadata }
 */
export const noIndexMetadata = {
  robots: {
    index: false,
    follow: false,
  },
} as const

// ─── Event JSON-LD builder ────────────────────────────────────────────────────

interface EventSeoFields {
  titulo: string
  descricao: string | null
  data_inicio: string
  data_fim?: string | null
  local?: string | null
  imagem_url?: string | null
  slug: string
  isPast?: boolean
}

/**
 * Builds an Event JSON-LD object from available event fields.
 * Only includes optional fields (location, image, endDate) when present.
 * Adds an @id equal to the canonical URL so search engines can deduplicate
 * the entity across pages.
 *
 * Embed the result as:
 *   <script type="application/ld+json">{JSON.stringify(result)}</script>
 */
export function buildEventJsonLd(evento: EventSeoFields): object {
  const eventUrl = canonicalUrl(`/eventos/${evento.slug}`)
  return {
    "@context": "https://schema.org",
    "@type": "Event",
    "@id": eventUrl,
    name: evento.titulo,
    ...(evento.descricao ? { description: evento.descricao } : {}),
    startDate: evento.data_inicio,
    ...(evento.data_fim ? { endDate: evento.data_fim } : {}),
    url: eventUrl,
    organizer: {
      "@type": "Organization",
      name: siteConfig.fullName,
      url: siteConfig.url,
    },
    ...(evento.local
      ? {
          location: {
            "@type": "Place",
            name: evento.local,
          },
        }
      : {}),
    ...(evento.imagem_url ? { image: evento.imagem_url } : {}),
    eventStatus: evento.isPast
      ? "https://schema.org/EventCompleted"
      : "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
  }
}

// ─── Breadcrumb JSON-LD builder ───────────────────────────────────────────────

interface BreadcrumbItem {
  name: string
  /** Absolute canonical URL — omit for the final (current) item */
  url?: string
}

/**
 * Builds a BreadcrumbList JSON-LD object.
 * Improves rich-result eligibility for detail pages.
 * Embed alongside Event or other entity JSON-LD as a second script block.
 *
 * @example
 *   buildBreadcrumbJsonLd([
 *     { name: "Eventos", url: canonicalUrl("/eventos") },
 *     { name: ev.titulo },
 *   ])
 */
export function buildBreadcrumbJsonLd(items: BreadcrumbItem[]): object {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      ...(item.url ? { item: item.url } : {}),
    })),
  }
}

// ─── Event list JSON-LD builder ───────────────────────────────────────────────

interface EventListItem {
  titulo: string
  slug: string
  position: number
}

/**
 * Builds an ItemList JSON-LD for the events archive page.
 * Helps search engines understand the archive as a structured list of events
 * and may improve sitelinks-style display in search results.
 * Limit to ~20 items to keep the payload lean.
 */
export function buildEventListJsonLd(items: EventListItem[]): object {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "Eventos – GŌKAI",
    url: canonicalUrl("/eventos"),
    itemListElement: items.map((item) => ({
      "@type": "ListItem",
      position: item.position,
      url: canonicalUrl(`/eventos/${item.slug}`),
      name: item.titulo,
    })),
  }
}

// ─── Article JSON-LD builder ──────────────────────────────────────────────────

interface ArticleSeoFields {
  titulo: string
  resumo: string
  slug: string
  publicado_em: string
  atualizado_em: string
  autor?: string
  imagem_url?: string | null
}

/**
 * Builds an Article JSON-LD object for a content hub article page.
 * Uses Schema.org Article type with author fallback to the organization.
 *
 * Embed as:
 *   <script type="application/ld+json">{JSON.stringify(result)}</script>
 */
export function buildArticleJsonLd(article: ArticleSeoFields): object {
  const articleUrl = canonicalUrl(`/conteudos/${article.slug}`)
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    "@id": articleUrl,
    headline: article.titulo,
    description: article.resumo,
    url: articleUrl,
    datePublished: article.publicado_em,
    dateModified: article.atualizado_em,
    author: {
      "@type": article.autor ? "Person" : "Organization",
      name: article.autor ?? siteConfig.fullName,
      ...(article.autor ? {} : { url: siteConfig.url }),
    },
    publisher: {
      "@type": "Organization",
      name: siteConfig.fullName,
      url: siteConfig.url,
    },
    ...(article.imagem_url ? { image: article.imagem_url } : {}),
    inLanguage: "pt-BR",
    isPartOf: {
      "@type": "WebSite",
      name: siteConfig.name,
      url: siteConfig.url,
    },
  }
}

// ─── Article list JSON-LD builder ─────────────────────────────────────────────

interface ArticleListItem {
  titulo: string
  slug: string
  position: number
}

/**
 * Builds an ItemList JSON-LD for the content hub index page.
 * Helps search engines understand the hub as a structured content collection.
 */
export function buildArticleListJsonLd(items: ArticleListItem[]): object {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "Conteúdos – GŌKAI",
    url: canonicalUrl("/conteudos"),
    itemListElement: items.map((item) => ({
      "@type": "ListItem",
      position: item.position,
      url: canonicalUrl(`/conteudos/${item.slug}`),
      name: item.titulo,
    })),
  }
}

// ─── LocalBusiness JSON-LD builder ───────────────────────────────────────────

interface LocalBusinessSeoFields {
  /** City name, e.g. "São Paulo" */
  cidade: string
  /** Neighborhood, e.g. "Pinheiros" (optional) */
  bairro?: string
  /** State abbreviation, e.g. "SP" */
  estado: string
  /** Full postal address (only include when real — omit if uncertain) */
  endereco?: string
  /** E.164 phone number (sourced from site.ts CONTACT_PHONE_HREF) */
  telefone?: string | null
  /** Contact email */
  email?: string | null
  /** Google Maps URL or directions link */
  mapaUrl?: string
  /** URL slug for this location page, e.g. "sao-paulo" */
  slug: string
}

/**
 * Builds a LocalBusiness / SportsClub JSON-LD object for a location landing page.
 *
 * Schema.org SportsClub is a subtype of LocalBusiness — it improves eligibility
 * for Google's local knowledge panel and maps integration.
 *
 * Only include this on confirmed location pages with real address data.
 * Omit `endereco`, `telefone`, and `email` by passing null/undefined — no fake
 * data will be emitted.
 *
 * Embed the result as:
 *   <script type="application/ld+json">{JSON.stringify(result)}</script>
 */
export function buildLocalBusinessJsonLd(fields: LocalBusinessSeoFields): object {
  const pageUrl = canonicalUrl(`/localidades/${fields.slug}`)
  const locationName = fields.bairro
    ? `${siteConfig.name} – ${fields.bairro}, ${fields.cidade}`
    : `${siteConfig.name} – ${fields.cidade}`

  return {
    "@context": "https://schema.org",
    "@type": "SportsClub",
    "@id": pageUrl,
    name: locationName,
    alternateName: siteConfig.fullName,
    url: pageUrl,
    parentOrganization: {
      "@type": "SportsOrganization",
      name: siteConfig.fullName,
      url: siteConfig.url,
    },
    // Address — only emitted when a confirmed address is supplied
    ...(fields.endereco
      ? {
          address: {
            "@type": "PostalAddress",
            streetAddress: fields.endereco,
            addressLocality: fields.cidade,
            addressRegion: fields.estado,
            addressCountry: "BR",
          },
        }
      : {}),
    // Contact — only emitted when real data is available
    ...(fields.telefone ? { telephone: fields.telefone } : {}),
    ...(fields.email ? { email: fields.email } : {}),
    // Maps link
    ...(fields.mapaUrl ? { hasMap: fields.mapaUrl } : {}),
    inLanguage: "pt-BR",
  }
}
